FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR '/app'
COPY requirements.txt ./

# Install `apt-get` deps.
RUN apt-get update && apt-get install -y \
        build-essential \
        python3 \
        python-dev \
        python3-dev \
        python-tk \
        python3-tk \
        python-opengl \
        curl \
        libsm6 \
        libxext6 \
        libglib2.0-0 \
        libxrender1 \
        wget \
        unzip

RUN apt-get install -y libgeos-dev

# Install libspatialindex (required for latest rtree).
RUN curl -L http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.gz | tar xz && \
    cd spatialindex-src-1.8.5 && \
    ./configure && \
    make && \
    make install && \
    ldconfig && \
    cd ..

RUN pip install -r requirements.txt 
COPY . .

EXPOSE 8000
ENTRYPOINT ["python3", "manage.py"]
CMD ["runserver","0.0.0.0:8000"]

